package vistas;

import dao.UsuarioDao;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author martin
 */
public class CrearUsuario extends JFrame {

    private JTextField campoUsuario;
    private JPasswordField campoPassword;
    private JButton botonRegistrar, botonCancelar;
    private JCheckBox checkboxMostrarContrasena;

    public CrearUsuario() {
        super("Registro - Ibiza Event Manager");
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Panel derecho con formulario
        JPanel panelDerecho = new JPanel(new GridBagLayout());
        panelDerecho.setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);

        // Imagen de perfil
        ImageIcon iconPerfil = new ImageIcon("src/main/java/recursos/loginperfil.png");
        JLabel lblImagenPerfil = new JLabel(new ImageIcon(iconPerfil.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        panelDerecho.add(lblImagenPerfil, gbc);

        // Título REGISTRO
        JLabel lblTitulo = new JLabel("REGISTRO");
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 24));
        lblTitulo.setForeground(new Color(0, 128, 128));
        gbc.gridy = 1;
        panelDerecho.add(lblTitulo, gbc);

        // Etiqueta Usuario
        gbc.gridwidth = 1;
        gbc.gridx = 0;
        gbc.gridy = 2;
        panelDerecho.add(new JLabel("Usuario:"), gbc);

        // Campo Usuario
        gbc.gridx = 1;
        campoUsuario = new JTextField(15);
        panelDerecho.add(campoUsuario, gbc);

        // Etiqueta Password
        gbc.gridx = 0;
        gbc.gridy = 3;
        panelDerecho.add(new JLabel("Contraseña:"), gbc);

        // Campo Contraseña
        gbc.gridx = 1;
        campoPassword = new JPasswordField(15);
        panelDerecho.add(campoPassword, gbc);

        // Botón Registrar
        botonRegistrar = new JButton("Registrar");
        botonRegistrar.setBackground(new Color(50, 205, 50)); // Verde
        botonRegistrar.setForeground(Color.WHITE);
        gbc.gridy = 4;
        panelDerecho.add(botonRegistrar, gbc);

        gbc.gridy = 5;
        checkboxMostrarContrasena = new JCheckBox("Mostrar contraseña");
        checkboxMostrarContrasena.setBackground(Color.WHITE);
        checkboxMostrarContrasena.setForeground(new Color(0, 128, 128));
        panelDerecho.add(checkboxMostrarContrasena, gbc);

        // Botón Cancelar
        botonCancelar = new JButton("Cancelar");
        botonCancelar.setBackground(new Color(255, 69, 0)); // Rojo
        botonCancelar.setForeground(Color.WHITE);
        gbc.gridy = 6;
        panelDerecho.add(botonCancelar, gbc);

        // Acción de botones
        botonRegistrar.addActionListener(e -> registrarUsuario());
        botonCancelar.addActionListener(e -> dispose());

        add(panelDerecho, BorderLayout.CENTER);
    }

    private void registrarUsuario() {
        String usuario = campoUsuario.getText();
        String contraseña = new String(campoPassword.getPassword());

        UsuarioDao usuarioDAO = new UsuarioDao();
        boolean registrado = usuarioDAO.registrarUsuario(usuario, contraseña);

        if (registrado) {
            JOptionPane.showMessageDialog(this, "Usuario registrado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose(); // Cierra la ventana de registro
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
