package vistas;

import Componentes.BotonColor;
import javax.help.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.net.URL;

/**
 *
 * @author martin
 */
public class PresentancionVista extends javax.swing.JFrame {

    /**
     * Creates new form PresentancionVista
     */
    public PresentancionVista() {
        super("Gestión de Eventos - Ibiza");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setUndecorated(true);

        // Panel con fondo degradado
        JPanel panel = new JPanel(new BorderLayout()) {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                GradientPaint gp = new GradientPaint(0, 0, new Color(65, 105, 225), getWidth(), getHeight(), new Color(65, 105, 225));
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };

        JLabel label = new JLabel("Bienvenido a Ibiza Events", SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.BOLD, 20));
        label.setForeground(Color.WHITE);

        // Botón "Continuar"
        BotonColor botonContinuar = new BotonColor("Continuar", Color.RED, Color.GREEN, Color.BLUE);
        botonContinuar.setFont(new Font("Arial", Font.BOLD, 26));
        botonContinuar.setForeground(Color.WHITE);
        botonContinuar.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        botonContinuar.setFocusPainted(false);

        // Botón Ayuda
        JButton botonAyuda = new JButton("Ayuda");
        botonAyuda.setFont(new Font("Arial", Font.BOLD, 16));
        botonAyuda.setBackground(new Color(255, 165, 0)); 
        botonAyuda.setForeground(Color.WHITE);
        botonAyuda.setFocusPainted(false);


        // Agregar evento para abrir la ayuda con F1
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_F1) {
                    mostrarAyuda(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, null));
                }
            }
        });
        setFocusable(true);

        botonAyuda.addActionListener(this::mostrarAyuda);

        // Logo
        ImageIcon originalLogo = new ImageIcon("src/main/java/recursos/hiibiza.jpg");
        Image img = originalLogo.getImage().getScaledInstance(500, 450, Image.SCALE_SMOOTH);
        JLabel logoLabel = new JLabel(new ImageIcon(img));

        // Panel de botones
        JPanel panelBotones = new JPanel();
        panelBotones.setBackground(new Color(65, 105, 225));
        panelBotones.add(botonAyuda);
        panelBotones.add(botonContinuar);

        panel.add(label, BorderLayout.NORTH);
        panel.add(logoLabel, BorderLayout.CENTER);
        panel.add(panelBotones, BorderLayout.SOUTH);

        add(panel);

        // Acción del botón continuar
        botonContinuar.addActionListener(e -> {
            dispose();
            new Login().setVisible(true);
        });
    }

    /**
     * Método para mostrar la ayuda con JavaHelp
     */
    private void mostrarAyuda(ActionEvent e) {
        try {
            // Use the classloader to load the helpset file from the classpath
            ClassLoader cl = PresentancionVista.class.getClassLoader();
            URL hsURL = getClass().getClassLoader().getResource("help/help_set.hs");

            if (hsURL == null) {
                throw new FileNotFoundException("No se encontró el archivo helpset.hs en el classpath.");
            }

            // Create the HelpSet and HelpBroker
            HelpSet hs = new HelpSet(null, getClass().getResource("/help/help_set.hs"));
            HelpBroker hb = hs.createHelpBroker();

            // Display the help
            hb.setDisplayed(true);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo cargar la ayuda: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentancionVista.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentancionVista.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentancionVista.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentancionVista.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentancionVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
